use exchange;

DELIMITER //
-- DROP PROCEDURE IF EXISTS SP_SORT;
CREATE PROCEDURE SP_SORT(INOUT PARAM_TABLA VARCHAR(32), INOUT PARAM_ORDENAR VARCHAR(32), INOUT PARAM_ASC_DESC VARCHAR(32))
BEGIN
    SET @t1 = CONCAT('SELECT * FROM ', PARAM_TABLA, ' U ORDER BY ', PARAM_ORDENAR, ' ', PARAM_ASC_DESC);
    PREPARE param_stmt FROM @t1;
    EXECUTE param_stmt;
    DEALLOCATE PREPARE param_stmt;
END //
DELIMITER ;
SET @PARAM_TABLA = 'USER';
SET @PARAM_ORDENAR = 'FirstName';
SET @PARAM_ASC_DESC = 'DESC';
CALL SP_SORT(@PARAM_TABLA, @PARAM_ORDENAR, @PARAM_ASC_DESC);

DELIMITER //
-- DROP PROCEDURE IF EXISTS SP_GetUsersWithWalletBalanceAboveThreshold;
CREATE PROCEDURE SP_GetUsersWithWalletBalanceAboveThreshold(IN threshold DECIMAL)
BEGIN
  SELECT U.UserId, CONCAT(U.FirstName, ' ', U.LastName) AS FullName, W.Balance AS WalletBalance
  FROM User U
  INNER JOIN Wallet W ON U.UserId = W.UserId
  WHERE W.Balance > threshold;
END  //
DELIMITER ;
SET @PARAM_UMBRAL = 0;
CALL SP_GetUsersWithWalletBalanceAboveThreshold(@PARAM_UMBRAL);